### ISSUE TITLE
[Bug]: Installation error Laravel 11.8.0

### ISSUE THREAD

**Issue by mahfoudfx** [njxqlus/filament-relation-manager-component#13]
### What happened?

Installation error message due to illuminate/contracts version.
Here is the error log:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires njxqlus/filament-relation-manager-component * -> satisfiable by njxqlus/filament-relation-manager-component[1.0.0, 1.0.1].
    - njxqlus/filament-relation-manager-component[1.0.0, ..., 1.0.1] require illuminate/contracts ^10.0 -> found illuminate/contracts[v10.0.0, ..., v10.48.11] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require njxqlus/filament-relation-manager-component:*" to figure out if any version is installable, or "composer require njxqlus/filament-relation-manager-component:^2.1" if you know which you need.

### How to reproduce the bug

Just install as described in the documentation
```php
composer require njxqlus/filament-relation-manager-component
``` 

### Package Version

1.0.1

### PHP Version

8.3.7

### Laravel Version

11.8.0

### Filament Version

3.2.82

**Comment by njxqlus** [comment]
Fixed in https://github.com/njxqlus/filament-relation-manager-component/releases/tag/1.0.2

**Comment by mahfoudfx** [comment]
Installation and Plugin are working like a charm, many thanks!
